name: Test build caching
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/cache-deps
              with:
                  workflow_name: test-build
                  workflow_cache: ${{ secrets.WORKFLOW_CACHE }}

            - uses: ./.github/actions/cache-turbo

            - uses: ./.github/actions/install-build
